---
- name: Add apt keys
  apt_key:
    url: "{{ key }}"
    state: present
  loop: "{{ apt_keys }}"
  loop_control:
    loop_var: key

- name: Add apt repositories
  apt_key:
    url: "{{ repo }}"
    state: present
  loop: "{{ apt_repositories }}"
  loop_control:
    loop_var: repo

- name: Add apt packages
  package:
    name: "{{ package }}"
    state: present
  loop: "{{ apt_packages }}"
  loop_control:
    loop_var: package

- name: Add .deb packages
  apt:
    deb: "{{ package }}"
  loop: "{{ deb_packages }}"
  loop_control:
    loop_var: package
