namespace: 3la
name: microcloud
version: 1.0.0
readme: README.md
authors:
- Tyler Weldon <tylerweldon94@gmail.com>
description: Configure a large variety of machines(Laptops, Desktops, Servers(virtual and/or baremetal), Pi's, etc.) to join a Hashicorp Nomad Cluster running over a Slack Nebula Network.
license:
- GPL-2.0-or-later
license_file: LICENSE
tags: [nomad, nebula, cloud]
repository: https://github.com/3-Letter-Agency/ansible-3la-microcloud
documentation: https://github.com/3-Letter-Agency/ansible-3la-microcloud/wiki
issues: https://github.com/3-Letter-Agency/ansible-3la-microcloud/issues
homepage: https://github.com/3-Letter-Agency/ansible-3la-microcloud
