storage:
  - name: Vault
    type: zfs
    mount_point_prefix: /
    raid_level: mirror
    ashift:
    devices:
      - ata-WDC_WD30EZRZ-00GXCB0_WD-WCC7K1JVUKYP
      - ata-WDC_WD30EZRZ-00GXCB0_WD-WCC7K2HU8KU1
network:
  type: ifupdown
  config: |
    auto lo
    iface lo inet loopback
    iface wlp5s0 inet auto
    auto enp4s0
    iface enp4s0 inet dhcp
    	post-up echo 1 > /proc/sys/net/ipv4/ip_forward
    	post-up echo 1 > /proc/sys/net/ipv4/conf/enp4s0/proxy_arp
    iface enp6s0 inet manual
    auto vmbr0
    iface vmbr0 inet static
    	address 10.0.0.2/24
    	gateway 10.0.0.1
    	bridge-ports enp4s0
    	bridge-stp off
    	bridge-fd 0
    	bridge-vlan-aware yes
    	bridge-vids 2-4094
    # Home LAN, bridged to physical NIC   
    auto vmbr1
    iface vmbr1 inet static
    	address 192.168.1.0/24
    	bridge-ports none
    	bridge-stp off
    	bridge-fd 0
    # hq-prod internal
    auto vmbr2
    iface vmbr2 inet static
    	address 192.168.2.0/24
    	bridge-ports none
    	bridge-stp off
    	bridge-fd 0
    # hq-test internal
    auto vmbr3
    iface vmbr3 inet static
    	address 192.168.3.0/24
    	bridge-ports none
    	bridge-stp off
    	bridge-fd 0
    # hq-dev internal
    auto vmbr66
    iface vmbr66 inet static
    	address 192.168.66.0/24
    	bridge-ports none
    	bridge-stp off
    	bridge-fd 0
    # shooting-range
    auto vmbr77
    iface vmbr77 inet static
    	bridge-ports none
    	bridge-stp off
    	bridge-fd 0
    # cleanroom
    auto vmbr88
    iface vmbr88 inet static
    	address 192.168.88.0/24
    	bridge-ports none
    	bridge-stp off
    	bridge-fd 0
    # frontline
users: 
  - name: director
    shell: /bin/bash
    groups:
      - sudo
    authorized_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDAQNNv2UpmEvU2XlGkw7dBRgP/JPUadnkbGMmayyfe2OIrb5JC0lAhOwjyNJxrTUWYcKNmeD2OzdSBrPKDHK0gGKEQOSnTwjgY7ex+yJVw33CuA9HoeljqJgmlGOvbg9O/h5JHg74dL8LQB0h/qq+ec+ifoI4yTLEJoPmD1qKP2k4obdEBl9yjmzQsT6vsBOixzc+fWy3gyy0Jj5m4adDKqeiX+twbQagoLiFc5IJxXCJMB4hYC7WDhY8rfsC+8VD6QEJS6KS8CnK8wZ5eQawd+ebE7X5OA7sZq0aYrBvgHPwWmgcunYQmqS16vlP1Dd3o//gs1b3mSHsA9qC7mEkJywxt7efOJnE4uuZVKWNCJsgo/y6pqqsKYHATJgAwX5R0uv1W27kJcVFNldywuSiN5vAPnbS9aznIEYEgUpUCbNz+BSjaq2D8EhpUgZSfk0IuZraPU6e6cQsjd6LyKUGc+S8vSyZQFwqS9h9lacE84cyvPYH5fKB8OkkmyUphzXZhtqA4sQR7Nfwn/GOk8S9gtTO9sL2KRBTSLOzHphOlR33gTGPKMpE0oQZa0SP7df0Kr3SjjBMy9w/0jjLbc/JYed1CeGWE9/30rKbPEpKacbfNcmpC3nEjUV1Hw5qXQ2hDhvtofArRHcxFhFmCPO0Olr6mXGG7bP8lvBcBr0gbEQ== director@headquarters1"
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC9yZlg7wYPxClZM5NumS8MonWPtuF85DasxbUBV9MUQVF7iDUBGmlnz2Cc5QZf5F27R5g+tm0CaghoT7V4FCH9AfuoslVR+8qtfCA2eCkJScQvBlUz1bhhtzqU8qH/tlcsZMaEj/NM+mo9OQYVUNx9nPghmUpVELIcOtxkPQn+YOS6kr6A10phf157HQcHgP91fgjMrncnCEYZhDq9+fRCNWGA6r3RZv683m3jFaYiS7sUDEGwIyFo/hc2HGpP/UTEbYOjHn+AyKCi5wK+9pPvCrFdiNcZrM6Y5FUiQLFLR9un9kczDhME2vLBkSU6FfuX1Ha6x8uqsZJK2cKIZNA4sn3xxti63I4UC/Q7CkJ8dLFFwA8wFq2RMnL19j1DvENI6dLLCRjPuqTTPcZmtoIaFdCCaRxD6CWL6c633NrMCzLQuvVkWU/AUYEUXTOjVVU3S1fl5nHGXo6ZwA3Ipxl6LTPFfipWv1A5/Y+yNJvhcSBH+bjGxuVuF/KmWatCS7tYXO4hdlELMlzcNdcjdFUlCGUf1fCgDOFaoViMFI1ccloCuxN9oNdWJFstU4DG6o6QInKDdELNqgJdAys6ExtSP0MbTnThJiKm5HVa7tII4bnJLWi7TUKhSILKwAwnkfCH121O846cB3st/GMR2hsFikUE98ra1K6G7pSYhaKMow=="
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCtJEIHPS6N87+8036zBwrsM5ZAbJ51AEUNNqefSXAFSgOEcSqBP6QMMKGCkqQsGtlGbEISIfpVN5v7+Mu+kSHtzpu6yDR/OTJCEI4yUsNdJEirwtit9tCS+nNIlv1RpUJIH800YH+sPHKziB4TTMkiKkqgaAHPqWo+0OdSreTQLzeTw9jpElEGu30xP1UnfTsrvd1p6Hvew9hN1Gn2OjKQhClH1YbqUr0V42HF9fv/8YgfEOxRWaTJbEDjWBOc7Xv2aHIzPGXW9VLFganHpDjtm0w5EklvENuGfRmntQNbg5cB8yStb45flTXNzuDVd5JFpJoFNwdbZNn8T+ONTTI1IKiPtoy8q9Yvto1ePd1HRdWaclWNZ9t5QxL0cb3w6LZR9L6iTLvbux0cE3rJ5uYlADHC5LBF7DTnkCjr+O0HyXYBm42I6zrwYa+omtgyFVII8aIClsEO4UZRNpNkaAwX8BUtFqAQPqyjCR8sD+PTqfpqfy/vIN2/ATDpKg2W/HDFhTKHTdyljp24tboj+CPfmQUg1ZQzMRlI2u1CSLqjcgyrjzztk/4k+NLQih7qoDuAt8ThSkmG97ZpQ5t44MiN1izW3nbYHRhNM4JNw5zPlVebKI0yXEk1o6o4Dk9T8YwHrlPTkLstBVq7iJ+wEqKbwrc7N9nfL7AjWHfmD/p8GQ== 3la-mobile"
proxmox_pools:
  - hq-dev
  - hq-test
  - hq-prod
  - shooting-range
  - cleanroom
  - frontline
proxmox_users:
  - templater
apt_repos:
  - gpg_key: https://pkgs.tailscale.com/stable/debian/bullseye.noarmor.gpg
    repo: "deb https://pkgs.tailscale.com/stable/debian bullseye main" 
apt_packages:
  - tailscale
