apiVersion: v1
kind: Secret
metadata:
  name: argocd-gh-pat
  namespace: argocd
type: Opaque
data:
  username: T29neQ==
  password: {{ k0s_argocd_github_pat }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: {{ k0s_argocd_default_apps_repo }}
      name: cne-default-yamls
      passwordSecret:
        name: argocd-gh-pat
        key: password
      usernameSecret:
        name: argocd-gh-pat
        key: username
  resource.customizations: |
    admissionregistration.k8s.io/MutatingWebhookConfiguration:
      ignoreDifferences: |
        jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
