- name: Create user account 
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.groups | join(',') }}"
    append: yes

- name: Set authorized_keys for user
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ key }}"
    state: present
  loop: "{{ item.authorized_keys }}"
  loop_control:
    loop_var: key

