---
apiVersion: v1
kind: Namespace
metadata:
  labels:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
  name: vm-images
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
  name: rook-ceph
