- name: Create Dummy Interface for Kube Router
  ansible.built.command: ip link add {{ k0s_dummy_nic }} type dummy
  when: {{ k0s_dummy_nic }} not in ansible_interfaces

- name: Add K0s IP to Dummy Interface
  ansible.built.command: ip addr add {{ k0s_dummy_ip }} dev {{ k0s_dummy_nic }}
  when: {{ k0s_dummy_ip }} not in ansible_all_ipv4_addresses

- name: Create K0sctl config dir
  file:
    name: "{{ k0sctl_config_dir }}"
    state: directory

- name: Template K0s Cluster Configuration
  template:
    src: templates/k0sctl.yaml.j2
    dest: "{{ k0sctl_config_dir }}/k0sctl.yaml"
  register: k0sctl_config
