# tasks file for creating Proxmox Users
- name: Get Proxmox Users
  ansible.builtin.command:
    argv:
      - /usr/bin/pvesh
      - ls
      - access/users
      - --output-format
      - json
  register: get_proxmox_users

- set_fact:
    cacheable: no
    current_proxmox_users: []

- set_fact:
   cacheable: no
   current_proxmox_users: "{{ current_proxmox_users + [user.name] if user.name not in current_proxmox_users else current_proxmox_users }}"
  loop: "{{ get_proxmox_users.stdout | from_json }}"
  loop_control:
    loop_var: user

- name: Create Proxmox Pools
  ansible.builtin.shell:
    cmd: "pvesh create access/users --userid {{ user }}@pam"
  loop: "{{ proxmox_users }}"
  loop_control:
    loop_var: user
  when: user not in current_proxmox_users

