- name: Check if aw(ansible-workstation) dir exists
  stat:
    path: "{{ aw_config_dir_path }}"
  register: stat_aw_config_dir

- name: Create aw config dir
  ansible.builtin.file:
    name: "/Users/{{ workstation_user }}/.config/aw"
    state: directory
  when: not stat_aw_config_dir.stat.exists

- name: Tap Hashicorp
  community.general.homebrew_tap:
    name: hashicorp/tap
    state: present

- name: Install Homebrew Packages
  homebrew:
    name: "{{ item }}"
    state: latest
  loop: "{{ homebrew_packages }}"

- name: Install Homebrew Cask Packages
  command: brew install --cask {{ item }}
  loop: '{{ homebrew_cask_packages }}'

- name: Homebrew Cleanup
  command: brew cleanup

- name: Add Custom Scripts and Bins
  ansible.builtin.copy:
    src: files/bin/
    dest: /usr/local/bin
    mode: '0755'

- name: Neovim configs 
  ansible.builtin.copy:
    src: files/config/nvim
    dest: "{{ ansible_user_dir }}/.config"
    owner: "{{ workstation_user }}"
    group: "{{ workstation_user }}"
    backup: true

- name: Set Workstation User shell
  ansible.builtin.user:
    name: "{{ workstation_user }}"
    shell: "{{ workstation_user_shell }}"
