---
# tasks file for roles/i3
- name: Copy i3-wm config
  ansible.builtin.copy:
    src: i3-config
    dest: "/home/{{ admin_user }}/.config/i3/config"
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: '0665'
  notify: reload i3

- name: Polybar config director
  ansible.builtin.file:
    path: "/home/{{ admin_user }}/.config/polybar"
    state: directory
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: '0755'

- name: Copy Polybar config
  ansible.builtin.copy:
    src: polybar-config
    dest: "/home/{{ admin_user }}/.config/polybar/config"
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: '0644'
  notify: reload i3


