- name: Check if virt image dir exists
  stat:
    path: "{{ qemu_image_base_path }}"
  register: stat_qemu_image_base_path

- name: Create virt image dir
  ansible.builtin.file:
    path: "{{ qemu_image_base_path }}"
    owner: "root"
    group: "root"
    mode: '0711'
    state: directory
  when: not stat_qemu_image_base_path.stat.exists

- name: Create virt image subdirectories
  ansible.builtin.file:
    path: "{{ qemu_image_base_path }}/{{ image.dir }}"
    owner: "root"
    group: "root"
    mode: '0711'
    state: directory
  when: qemu_image_urls is not []
  loop: "{{ qemu_image_urls }}"
  loop_control:
    loop_var: image

- name: Download virt images
  ansible.builtin.get_url:
    url: "{{ image.url }}"
    dest: "{{ qemu_image_base_path }}/{{ image.image_dir }}"
    mode: '0444'
  loop: "{{ qemu_image_urls }}"
  loop_control:
    loop_var: image
