#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    colorscheme = "onedark"
    colorscheme_bg = "dark"
    enable_guicolors = true
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = "colorscheme"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

[[layers]]
  name = "debug"

[[layers]]
name = "fzf"

[[layers]]
  name = "git"

[[layers]]
  name = "github"

[[layers]]
  name = "lsp"

[[layers]]
  name = "ssh"

[[layers]]
  name = "tmux"

[[layers]]
  name = "tools"

[[layers]]
  name = "treesitter"

[[layers]]
  name = "ui"

[[layers]]
  name = "lang#crystal"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#elixir"

[[layers]]
  name = "lang#erlang"

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#graphql"

[[layers]]
  name = "lang#latex"

[[layers]]
  name = "lang#lisp"

[[layers]]
  name = "lang#lua"

[[layers]]
  name = "lang#matlab"

[[layers]]
  name = "lang#python"

[[layers]]
  name = "lang#rust"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#wolfram"
