- name: Check if Pool Exists
  stat:
    path: "{{ zfs_pool_mount_point }}"
  register: stat_zfs_pool_mount_point

- name: Create ZFS Pool
  command: >-
    zpool create -f 
    -o ashift={{ zfs_pool_ashift }}
    -m {{ zfs_pool_mount_point }}
    {{ zfs_pool_name }}
    {{ zfs_pool_device_type }}
    {{ zfs_pool_disk_ids | join(' ') }}
  when: not stat_zfs_pool_mount_point.stat.exists
