- name: Template Nomad configuration
  ansible.builtin.template:
    src: templates/config.hcl.j2
    dest: "{{ nomad_config_path }}"
    owner: nomad
    group: nomad
    mode: '0644'
  notify: reload nomad

- name: Start Nomad
  ansible.builtin.systemd:
    name: nomad
    state: started
    enabled: yes
