---
# tasks file for ansible/roles/argocd
- name: Deploy ENTRYPOINT ArgoCD AppOfApps
  kubernetes.core.helm:
    name: replicator-entrypoint
    chart_ref: "{{ role_path }}/files/apps/entrypoint"
    release_namespace: replicator-entrypoint
