---
apiVersion: v1
kind: Namespace
metadata:
  labels:
  name: monitoring
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 43.1.1
    helm:
      releaseName: gorgon-stare
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
