---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/oogy/replicator
    targetRevision: HEAD
    path: "k8s/apps/plex"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: plex
  syncPolicy:
    syncOptions:     
      - CreateNamespace=true
