---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
spec:
  project: default
  source:
    chart: rook-ceph
    repoURL: https://charts.rook.io/release
    targetRevision: 1.10.7
    helm:
      releaseName: rook-ceph
  destination:
    server: "https://kubernetes.default.svc"
    namespace: rook-ceph
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
    syncOptions:     
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ceph-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/oogy/replicator
    targetRevision: HEAD
    path: k8s/apps/ceph-cluster
  destination:
    server: "https://kubernetes.default.svc"
    namespace: rook-ceph
#---
# make a chart in k8s/apps/cep-cluster
# add a cluster.yaml from https://raw.githubusercontent.com/rook/rook/release-1.9/deploy/examples/cluster.yaml in k8s/apps/ceph-cluster/templates
# point to k8s/apps/ceph-cluster in a new app here
