- name: Install Nebula
  ansible.builtin.unarchive:
    src: "https://github.com/slackhq/nebula/releases/download/v{{ nebula.version }}/nebula-linux-amd64.tar.gz"
    dest: '{{ nebula.install_path }}'
    remote_src: yes
    mode: '0755'
    owner: 'root'
    group: 'root'

- name: Nebula Configuration Directory
  ansible.builtin.file:
    path: '{{ nebula.config_dir }}'
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: Configure nebula
  ansible.builtin.template:
    src: templates/config.j2
    dest: '{{ nebula.config_dir }}/config.yml'
    owner: root
    group: root
    mode: '0644'
