- name: Template Out Wireguard Config(s)
  template:
    src: templates/wireguard.conf.j2
    dest: /etc/wireguard/{{ interface.name }}.conf
  loop: "{{ wireguard.interfaces|flatten(levels=1) }}"
  loop_control:
    loop_var: interface
    index_var: idx
  ignore_errors: True
  no_log: True
  register: wg_template

- debug:
    msg: '{{ wg_template.template_result[idx].msg | regex_replace(interface.private_key) }}'
  loop: wg_template.results
  loop_control:
    loop_var: template_result
    index_var: idx

- fail:
    msg: "Error templating Wireguard Config"
  when: wg_template.results[idx].failed
  loop: wg_template.results
  loop_control:
    loop_var: template_result
    index_var: idx
