- name: Create Dummy Interface for Kube Router
  ansible.builtin.command: ip link add {{ k0s.dummy.nic }} type dummy
  when: k0s.dummy.nic not in ansible_interfaces

- name: Add K0s IP to Dummy Interface
  ansible.builtin.command: ip addr add {{ k0s.dummy.ip }} dev {{ k0s.dummy.nic }}
  when: k0s.dummy.ip not in ansible_all_ipv4_addresses

- name: Create K0sctl config dir
  file:
    name: "{{ k0s.k0sctl.config_dir }}"
    state: directory

- name: Template K0s Cluster Configuration
  template:
    src: templates/k0sctl.yaml.j2
    dest: "{{ k0s.k0sctl.config_dir }}/k0sctl.yaml"
  register: k0sctl_config
